spring:
  application:
    name: FluxWard
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      redis:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        register-health-indicator: true

rate-limiter:
  capacity: 100
  refill-rate-per-second: 10
  window-ms: 60000
  fail-open: true
  key-type: API_KEY
  algorithm: TOKEN_BUCKET
  jwt:
    secret: "my-secret-key-but-it-must-be-at-least-32-characters-long"
  routes:
    - path: /test/fixedwindow
      algorithm: FIXED_WINDOW
      capacity: 10
      refill-rate-per-second: 10
      window-ms: 60000
      key-type: API_KEY
    - path: /test/slidingwindow
      algorithm: SLIDING_WINDOW
      capacity: 30
      refill-rate-per-second: 10
      window-ms: 10000
      key-type: JWT_SUBJECT
